### PR TITLE
Bug fix release 4.0.1

### LINKED ISSUE #33: When using a before notification Remote_file in install freaks out
because the zip file hasn't been extracted yet while checking to run the before notification the resource freaks out and crashes the chef run.

Need to add a test to catch this and also apply the fix which is adding the following line to the remote_file resource:

`only_if {::File.exist?("#{Chef::Config[:file_cache_path]}/#{basename}/#{system}/nssm.exe")}`

will make the change as soon as i'm done some more local testing.

### LINKED ISSUE #34: NSSM create an Error event when dumping info
Hello,

Every time the *nssm_service* tries to dump service info using the `nssm dump` command, it creates an Error in the windows event log:
> Failed to open registry key HKLM\SYSTEM\CurrentControlSet\Services\_-MARKER-_: The data area passed to a system call is too small.

The *dump* command allow an undocumented extra argument to replace the original service name by the specified one. The `load_current_value` method of the `nssm_service` resource is leveraging this feature with a hardcoded *\_-MARKER-\_* value to dump the parameters.
I think the implementation of this feature performs a lookup of the *\_-MARKER-\_* service, which doesn't exist and trigger the event log creation.

I'll open a PR to fix that.

*Cc.* @aboten

### PR DESCRIPTION
**Pull request by axelrtgs**
## 4.0.1 2018-01-24

- Remote file is now before notification friendly (fixes #33)
- Stop using non-documented argument for nssm dump (fixes #34)
- Fixed a bug where AppExit needs a subparameter on reset 
- Updated URLs to new repo location, changelog and  version bump

### CODE REVIEW

File: resources/install.rb [hunk 1]
```diff
@@ -24,6 +24,7 @@
   remote_file 'install nssm' do
     path ::NSSM.binary_path node
     source "file:///#{system_file}"
+    only_if {::File.exist?("#{Chef::Config[:file_cache_path]}/#{basename}/#{system}/nssm.exe")}
```
Comment (Annih) [inline resources/install.rb]: Why is it notification friendly?
Notification are bypassing only_if/not_if guards.

In a separate PR, could you explain clearly the initial bug (I didn't encounter it) and the resolution?

Comment (axelrtgs) [reply resources/install.rb]: It fixes #33 let me know if enough details are in there. It only happens when you use a before notification, the other types work.

I am trying to see how to split the commits into separate PR's and submit them separately but my GIT isn't very strong.

**Comment by axelrtgs** [comment]
I think i managed to get something working for the other PRs. i opened two more one for each bug fix to be merged. i dont think i can edit this one, but if we squash merge it should look much cleaner in the commit history since now with the other PRs the commit messages would be duplicated.
